{
 "title": "Messaging Metrics",
 "description": "Messaging Related Metrics Per Namespace",
 "tags": [
  "messaging",
  "namespaces"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "pulsar_rate_in{cluster=~\".+\"}"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "pulsar_rate_in{namespace=~\".+\", cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "pulsar_storage_size{namespace=~\"$namespace\", topic=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_topics_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{cluster=~\"$cluster\", job=~\".*broker\",  namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_subscriptions_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_consumers_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Msg Backlog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Local publish rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "msg/s" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_rate_in{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) by (cluster, namespace)",
       "legendFormat": "{{cluster}} - {{namespace}}"
      }
     ]
    },
    {
     "title": "Local delivery rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short", "label": "msg / s" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_rate_out{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) by (cluster, namespace)",
       "legendFormat": "{{cluster}} - {{namespace}}"
      }
     ]
    },
    {
     "title": "Local publish throughput (bytes/s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_throughput_in{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) by (cluster, namespace)",
       "legendFormat": "{{cluster}} - {{namespace}}"
      }
     ]
    },
    {
     "title": "Local delivery throughput (bytes/s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_throughput_out{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) by (cluster, namespace)",
       "legendFormat": "{{cluster}} - {{namespace}}"
      }
     ]
    },
    {
     "title": "Topics - Producers - Subscriptions - Consumers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "count" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_topics_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
       "legendFormat": "topics"
      },
      {
       "expr": "sum(pulsar_producers_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
       "legendFormat": "producers"
      },
      {
       "expr": "sum(pulsar_subscriptions_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
       "legendFormat": "subscriptions"
      },
      {
       "expr": "sum(pulsar_consumers_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
       "legendFormat": "consumers"
      }
     ]
    },
    {
     "title": "Local backlog",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Messages" }
     ],
     "targets": [
      {
       "expr": "sum(pulsar_msg_backlog{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) by (cluster, namespace)",
       "legendFormat": "{{cluster}} - {{namespace}}"
      }
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Storage Write Rate",
   "type": "graph",
   "description": "Rate of writes into storage (can be lower than publish rate, when batching is enabled)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "entry / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
     "legendFormat": "$namespace"
    }
   ]
  },
  {
   "title": "Storage read entry rate",
   "type": "graph",
   "description": "Reads from bookies",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "entries / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_read_latency_count{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
     "legendFormat": "read rate"
    }
   ]
  },
  {
   "title": "Storage entry size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_entry_size_le_128{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 128 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_512{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 512 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_kb{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 1 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_2_kb{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 2 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_4_kb{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 4 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_16_kb{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 16 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_100_kb{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 100 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_mb{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "< 1 MB"
    },
    {
     "expr": "sum(pulsar_entry_size_overflow{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) / 60.0",
     "legendFormat": "> 1 MB"
    }
   ]
  },
  { "title": "Geo Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Incoming replication rate | any → $cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_rate_in{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\", remote_cluster!=\"local\"}) by (cluster, remote_cluster)",
     "legendFormat": "{{remote_cluster}} → {{cluster}}"
    }
   ]
  },
  {
   "title": "Outgoing replication rate | $cluster → any",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_rate_out{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"})",
     "legendFormat": "{{cluster}} → {{remote_cluster}}"
    }
   ]
  },
  {
   "title": "geo-replication-throughput(MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(pulsar_replication_throughput_out{namespace=~\"$namespace\"})/1024/1024",
     "legendFormat": "pulsar_replication_throughput_out"
    },
    {
     "expr": "sum(pulsar_replication_throughput_in{namespace=~\"$namespace\"})/1024/1024",
     "legendFormat": "pulsar_replication_throughput_in"
    }
   ]
  },
  {
   "title": "Replication backlog | $cluster → any",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_replication_backlog{cluster=~\"$cluster\", job=~\".*broker\", namespace=~\"$namespace\"}) by (cluster, remote_cluster)",
     "legendFormat": "{{cluster}} → {{remote_cluster}}"
    }
   ]
  }
 ]
}